create database CharityWebsite
use CharityWebSite

CREATE TABLE ACCOUNT(
	ACCOUNT_ID INT IDENTITY(1,1) NOT NULL,
	USERNAME varchar(50) NOT NULL,
	EMAIL VARCHAR(150) NOT NULL,
	PASSWORD VARCHAR(50) NOT NULL,
	BIRTH SMALLDATETIME NOT NULL,
	ROLE INT NOT NULL DEFAULT(0),
	CONSTRAINT PK_ACCOUNT PRIMARY KEY(ACCOUNT_ID)
);
CREATE TABLE CHARITY_CATEGORIES(
	ID_CATEGORIES INT IDENTITY(1,1) NOT NULL,
	NAME_CATEGORIES NVARCHAR(100) NOT NULL,
	DESCRIPTION NVARCHAR(300) NOT NULL,
	CONSTRAINT PK_CH_CATEGORIES PRIMARY KEY (ID_CATEGORIES)
)
CREATE TABLE CHARITY(
	CHARITY_ID INT IDENTITY(1,1) NOT NULL,
	CHARITY_NAME NVARCHAR(200) NOT NULL,
	CHARITY_CONTENT NVARCHAR(MAX) NOT NULL,
	CHARITY_START DATETIME NOT NULL,
	CHARITY_END DATETIME NOT NULL,
	CHARITY_TARGET MONEY NOT NULL,
	CHARITY_PROCESS MONEY NOT NULL,
	CHARITY_ACCOUNT INT NOT NULL,
	PAY_METHOD NVARCHAR(200) NOT NULL,
	ACCOUNT_ID INT,
	STATUS BIT NOT NULL DEFAULT(1),
	ID_CATEGORIES INT NOT NULL,
	CONSTRAINT PK_CHARITY PRIMARY KEY(CHARITY_ID),
	CONSTRAINT FK_CHARITY_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
	CONSTRAINT FK_CHARITY_CATEGORIES FOREIGN KEY (ID_CATEGORIES) REFERENCES CHARITY_CATEGORIES(ID_CATEGORIES)
	ON DELETE CASCADE
	ON UPDATE CASCADE
);
CREATE TABLE CHARITY_DETAIL(
	ID_CH_DETAIL INT IDENTITY(1,1) NOT NULL,
	CHARITY_ID INT NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	CASH MONEY NOT NULL,
	DATE_PAY DATETIME DEFAULT(GETDATE()),
	PAY_METHOD NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_CH_DETAIL PRIMARY KEY (ID_CH_DETAIL),
	CONSTRAINT FK_CHDETAIL_CHARITY FOREIGN KEY (CHARITY_ID) REFERENCES CHARITY(CHARITY_ID),
	CONSTRAINT FK_CHDETAIL_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES ACCOUNT(ACCOUNT_ID),
);
CREATE TABLE NEWS_CATEGORIES(
	ID_CATEGORIES INT IDENTITY(1,1) NOT NULL,
	NAME NVARCHAR(200) NOT NULL,
	DESCRIPTION NVARCHAR(200) NOT NULL,
	CONSTRAINT PK_NEWSCAT PRIMARY KEY (ID_CATEGORIES)
)
CREATE TABLE NEWS(
	ID_NEWS INT IDENTITY(1,1) NOT NULL,
	TITLE NVARCHAR(200) NOT NULL,
	CONTENT NVARCHAR(MAX) NOT NULL,
	DATE_PUSH DATETIME NOT NULL,
	ACCOUNT_ID INT NOT NULL,
	COUNTVIEW INT NOT NULL,
	ID_CATEGORIES INT NOT NULL,
	CONSTRAINT PK_NEWS PRIMARY KEY (ID_NEWS),
	CONSTRAINT FK_NEWS_CATE FOREIGN KEY (ID_CATEGORIES) REFERENCES NEWS_CATEGORIES
)


